[tool.ruff]
# consider adding "B", "ARG"
select = ["C", "C4", "E", "F", "I", "ICN", "N", "PLC", "PLE", "PLR", "PLW", "Q", "RET", "RUF", "SIM", "W", "YTT"]
extend-ignore = ["PLR0913"]

[tool.ruff.per-file-ignores]
"tests/**/test_*.py" = ["F841", "C901"]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
markers = [
    "appstore: needs appstore pod",
    "authz: needs authz-server",
    "discovery: needs cloud-discovery",
    "keycloak: needs keycloak pod",
    "mlops: needs mlops pod",
    "featurestore: needs featurestore pod",
    "redis: needs redis pod",
    "kafka: needs kafka pod",
]
addopts = "-p k8spec.pytest --strict-markers --spec --alluredir reports/allure"
